include ../common/ver_defs.mk

MAIN = $(EE_PORTING__MAIN)
VERSION = $(EE_PORTING__VER)
MAIN_NAME = $(EE_PORTING__MAIN_NAME)_$(EE_PORTING__VER)
PHP_DEPS += dynamic-man.php

include ../common/manual.mk
include ../common/php_man.mk
