include ../common/ver_defs.mk

MAIN = $(FLEX_REFMAN__MAIN)
VERSION = $(FLEX_REFMAN__VER)
MAIN_NAME = $(FLEX_REFMAN__MAIN_NAME)_$(FLEX_REFMAN__VER)
PHP_DEPS += dynamic-man.php

include ../common/manual.mk
include ../common/php_man.mk
