include ../common/ver_defs.mk

MAIN = $(FLEX_SCICOS__MAIN)
VERSION = $(FLEX_SCICOS__VER)
MAIN_NAME = $(FLEX_SCICOS__MAIN_NAME)_$(FLEX_SCICOS__VER)
PHP_DEPS += dynamic-man.php

include ../common/manual.mk
include ../common/php_man.mk
