include ../common/ver_defs.mk

MAIN = $(ARCH_PIC30__MAIN)
VERSION = $(ARCH_PIC30__VER)
MAIN_NAME = $(ARCH_PIC30__MAIN_NAME)_$(ARCH_PIC30__VER)
PHP_DEPS += dynamic-man.php

include ../common/manual.mk
include ../common/php_man.mk
