include ../common/ver_defs.mk

MAIN = $(RTDRUID_REFMAN__MAIN)
VERSION = $(RTDRUID_REFMAN__VER)
MAIN_NAME = $(RTDRUID_REFMAN__MAIN_NAME)_$(RTDRUID_REFMAN__VER)
PHP_DEPS += dynamic-man.php

include ../common/manual.mk
include ../common/php_man.mk
