include ../common/ver_defs.mk

MAIN = $(ARCH_NIOS2_FIFO_TUTORIAL__MAIN)
VERSION = $(ARCH_NIOS2_FIFO_TUTORIAL__VER)
MAIN_NAME = $(ARCH_NIOS2_FIFO_TUTORIAL__MAIN_NAME)_$(ARCH_NIOS2_FIFO_TUTORIAL__VER)
PHP_DEPS += dynamic-man.php

include ../common/manual.mk
include ../common/php_man.mk
