include ../common/ver_defs.mk

MAIN = $(EE_COM_REFMAN__MAIN)
VERSION = $(EE_COM_REFMAN__VER)
MAIN_NAME = $(EE_COM_REFMAN__MAIN_NAME)_$(EE_COM_REFMAN__VER)
PHP_DEPS += dynamic-man.php

include ../common/manual.mk
include ../common/php_man.mk
