include ../common/ver_defs.mk

MAIN = $(EE_BASIC_REFMAN__MAIN)
VERSION = $(EE_BASIC_REFMAN__VER)
MAIN_NAME = $(EE_BASIC_REFMAN__MAIN_NAME)_$(EE_BASIC_REFMAN__VER)
PHP_DEPS += dynamic-man.php

include ../common/manual.mk
include ../common/php_man.mk
